baseURL = 'https://sv-haimbach-rodges-de.web.app/'
languageCode = 'de-DE'
title = 'Schützenverein "Gut Schuß" Haimbach/Rodges'
theme = 'hugo-universal-theme'

defaultContentLanguage = "de"
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

assetDir = "static"

timeout = "120s"

[menu]


# Main menu
[[menu.main]]
    name       = "Startseite"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    name       = "Aktuelles"
    identifier = "menu.blog"
    url        = "/blog"
    weight     = 2

[[menu.main]]
    name       = "Jugend"
    identifier = "menu.jugend"
    url        = "/jugend"
    weight     = 3

[[menu.main]]
    name       = "Historie"
    identifier = "menu.historie"
    url        = "/historie"
    weight     = 4

[[menu.main]]
    name       = "Bilder"
    identifier = "menu.gallery"
    url        = "/gallery"
    weight     = 5

[params]
    viewMorePostLink = "/blog/"
    author = "Schneider"
    defaultKeywords = ["Schützenverein", "Fulda", "Haimbach", "Rodges", "Schießsport"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by Devcows using Hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = ""

    latitude = ""
    longitude = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>Der Schützenverein \"Gut Schuß\" wurde 1986 gegründet und engagiert sich seitdem im Schießsport mit Luftgewehr und Luftpistole.</p>"
    copyright = "Copyright (c) 2024, Schützenverein \"Gut Schuß\" Haimbach/Rodges 1986 e.V."

    # Format dates with Go's time formatting
    date_format = "2. Januar 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Schützenverein \"Gut Schuß\" Haimbach/Rodges"

    logo = "img/wappen.png"
    logo_small = "img/wappen.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Schützenverein "Gut Schuß" Haimbach/Rodges</strong>
        <br>Bürgerhaus Haimbach
        <br>Hirschweg 17
        <br>36041 Fulda
      </p>
      """
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Aktuelles"
    subtitle = ""
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

